variable "parent_id" {
  type        = string
  description = "The GCP Folder or Organization ID where the global Model Armor Floor Setting will be enforced (e.g., 'folders/123456' or 'organizations/789012')."
}

variable "target_projects" {
  type        = list(string)
  description = "List of GCP project IDs where Model Armor will be deployed. Typically generated by discover.py."
  default     = []
}

variable "location" {
  type        = string
  description = "GCP regional location for the Model Armor templates."
  default     = "us-central1"
}

variable "pii_inspection_enabled" {
  type        = bool
  description = "Flag to enable or disable Sensitive Data Protection (PII) inspection."
  default     = true
}

variable "log_template_operations" {
  type        = bool
  description = "Enables operational audit logging for Model Armor templates."
  default     = true
}

variable "log_sanitize_operations" {
  type        = bool
  description = "Enables data-plane logging of prompt and response sanitization details (contains full payloads)."
  default     = false
}
